#!/bin/bash
status=$(nordvpn status | head -n2 | tail -n1 | awk '{print $3}')

if [ "$status" == "Connected" ]; then 
	alacritty -e nordvpn d
	echo "#90c861" > ~/tmp/xmonad/vpnstat-hex
else 
	alacritty -e nordvpn c
	echo "#D35D6E" > ~q/tmp/xmonad/vpnstat-hex
fi
