#!/bin/bash
status=$(nordvpn status | head -n2 | tail -n1 | awk '{print $3}')

if [ "$status" == "Connected" ]; then 
	echo "#90c861" > ~/tmp/xmonad/vpnstat-hex
else 
	echo "#D35D6E" > ~/tmp/xmonad/vpnstat-hex
fi
